language: node_js

node_js:
  - "6"

before_script:
  - npm install -g gulp
  - npm install express-generator -g
  - npm install --save mocha
  - npm install --global gulp-cli
  - npm install --save gulp gulp-apidoc jshint gulp-jshint gulp-mocha

script: gulp
